import type { Metadata } from "next";
import "./globals.css";
import Link from "next/dist/client/link";
import { AiOutlineInstagram } from "react-icons/ai";
import { FaLinkedinIn } from "react-icons/fa6";
import { FaXTwitter } from "react-icons/fa6";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">

        <header className="py-2">
          <nav className="flex flex-col sm:flex-row sm:items-center sm:justify-between text-black px-4 py-3 gap-3">
            <div>
              <h3 className="text-xl text-black font-bold">
                <span className="text-yellow-500">Aura</span>Commerce
              </h3>
            </div>
            <div>
              <ul className="flex flex-col sm:flex-row sm:space-x-4 space-y-2 sm:space-y-0">
                <li className="text-black hover:text-gray-800"><Link href="/">Home</Link></li>
                <li className="text-black hover:text-gray-800"><Link href="/about">About</Link></li>
                <li className="text-black hover:text-gray-800"><Link href="/products">Products</Link></li>
              </ul>
            </div>
          </nav>
        </header>
        <main className="flex-1">{children}</main>

        <footer className=" text-white px-6 py-10 mt-8">
          <div className="max-w-7xl mx-auto">
            <div className="flex flex-col gap-10 lg:flex-row lg:items-start lg:justify-between">

              {/* left side about us and social media links */}
              <div className="lg:w-1/3 mt-2">
                <p className="text-sm text-black mb-6">
                  Our website is designed to help you discover and compare the best products with confidence. We provide up-to-date information, easy navigation, and reliable support for every step of your buying journey.
                </p>
                <div className="flex flex-wrap gap-3 text-slate-400 text-sm">
                  <span className="inline-flex items-center justify-center rounded-full border border-slate-900 px-3 py-2 cursor-pointer"><AiOutlineInstagram  color="black"/></span>
                  <span className="inline-flex items-center justify-center rounded-full border border-slate-900 px-3 py-2 cursor-pointer"><FaLinkedinIn  color="black"/></span>
                  <span className="inline-flex items-center justify-center rounded-full border border-slate-900 px-3 py-2 cursor-pointer"><FaXTwitter color="black"/></span>
                </div>
              </div>

                {/* products and other stuff */}
              <div className="flex flex-col gap-8 justify-between sm:flex-row sm:justify-between lg:w-2/3">
                <div className="flex-1">
                  <h3 className="text-sm  uppercase tracking-[0.16em] text-yellow-500 font-bold mb-4">Company</h3>
                  <ul className="space-y-3 text-sm text-black">
                    <li className="cursor-pointer hover:opacity-75">About</li>
                    <li className="cursor-pointer hover:opacity-75">Blog</li>
                    <li className="cursor-pointer hover:opacity-75">Careers</li>
                  </ul>
                </div>
                <div className="flex-1">
                  <h3 className="text-sm  uppercase tracking-[0.16em] text-yellow-500 font-bold mb-4">Resources</h3>
                  <ul className="space-y-3 text-sm text-black">
                    <li className="cursor-pointer hover:opacity-75">Documentation</li>
                    <li className="cursor-pointer hover:opacity-75">Guides</li>
                    <li className="cursor-pointer hover:opacity-75">API Reference</li>
                  </ul>
                </div>
                <div className="flex-1">
                  <h3 className="text-sm  uppercase tracking-[0.16em] text-yellow-500 font-bold mb-4">Product</h3>
                  <ul className="space-y-3 text-sm text-black">
                    <li className="cursor-pointer hover:opacity-75">Features</li>
                    <li className="cursor-pointer hover:opacity-75">Pricing</li>
                    <li className="cursor-pointer hover:opacity-75">Enterprise</li>
                  </ul>
                </div>
              </div>
            </div>

            <div className="mt-10 border-t border-slate-800 pt-6 flex flex-col gap-5 md:flex-row md:items-center md:justify-between">
              <p className="text-sm text-slate-400">© 2026 AuraCommerce. All rights reserved.</p>
              <ul className="flex flex-wrap gap-4 text-sm text-black">
                <li className="cursor-pointer hover:opacity-75">Privacy</li>
                <li className="cursor-pointer hover:opacity-75">Terms</li>
                <li className="cursor-pointer hover:opacity-75">Security</li>
                <li className="cursor-pointer hover:opacity-75">Status</li>
              </ul>
            </div>
          </div>
        </footer>

      </body>
    </html>
  );
}
